apiVersion: mlflow.trendyol.com/v1beta1
kind: MLFlow
metadata:
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow-sample
    app.kubernetes.io/part-of: mlflow-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mlflow-operator
  name: mlflow-sample
spec:
  image: erayarslan/mlflow:v2.6.0
  modelSyncPeriodInMinutes: 1
  modelImage: erayarslan/mlflow_serve:v2.6.0-conda
  configMapName: mlflow-cm
  replicas: 1
